import { staticCardIndex, type CardIndex, type Domain, type Zone } from "@forge/engine";
import poolJson from "./data/pool.json";

/**
 * `F2`'s card pool — a static file, generated by `scripts/build-f2-pool.mjs` from the
 * official gallery data in `data/cards.json` (PLAN.md §4).
 *
 * One Legend, ~30 owned names. `F3` replaces this with all 1,180 printings; until then
 * the bundle stays at tens of KB and the whole app loads instantly on a phone.
 */

export interface PoolCard {
  name: string;
  domains: Domain[];
  energy: number | null;
  power: number | null;
  might: number | null;
  types: string[];
  superTypes: string[];
  text: string;
  imageUrl: string;
}

const pool = poolJson as unknown as {
  legendCardId: string;
  chosenChampionCardId: string;
  cards: Record<string, PoolCard>;
  collection: Record<string, number>;
};

export const CARDS: Record<string, PoolCard> = pool.cards;
export const LEGEND_CARD_ID = pool.legendCardId;
export const CHAMPION_CARD_ID = pool.chosenChampionCardId;

/** What you physically own, keyed on printing — the F2 stand-in for `W2`. */
export const COLLECTION: Record<string, number> = pool.collection;

export const cardIndex: CardIndex = staticCardIndex(CARDS);

export const cardOf = (cardId: string): PoolCard | undefined => CARDS[cardId];

/**
 * Which zone a printing belongs in, from its card type.
 *
 * Runes and battlefields are registered separately from the Main Deck and are counted by
 * different rules (L4, L5), so a card cannot simply be "added to the deck" — it has a
 * home. Deriving that from the type means the UI never has to ask.
 */
export function zoneFor(card: PoolCard): Zone {
  if (card.types.includes("rune")) return "RUNE";
  if (card.types.includes("battlefield")) return "BATTLEFIELD";
  return "MAIN";
}

/** Collection printings, ordered the way you would look for them: by zone, then cost. */
export const OWNED_IDS: string[] = Object.keys(COLLECTION).sort((a, b) => {
  const left = CARDS[a];
  const right = CARDS[b];
  if (!left || !right) return a.localeCompare(b);
  const zones: Zone[] = ["MAIN", "RUNE", "BATTLEFIELD"];
  const byZone = zones.indexOf(zoneFor(left)) - zones.indexOf(zoneFor(right));
  if (byZone !== 0) return byZone;
  const byEnergy = (left.energy ?? 99) - (right.energy ?? 99);
  return byEnergy !== 0 ? byEnergy : left.name.localeCompare(right.name);
});
