#!/usr/bin/env node
/**
 * D-068 step 2 — normalise what was read from the field into `data/field.json`.
 *
 * **Collection is Claude reading a page at a human pace; this script only normalises it.**
 * The captures under `data/field/` are the pages as read, committed so every figure in the
 * snapshot can be traced back to one line of text and re-derived without touching the site.
 *
 * ⚠️ **It refuses to write a matrix that disagrees with itself.** Every "A vs B" cell must be
 * the mirror of "B vs A". A capture copied out of a page in chunks is exactly where a shifted
 * comma turns Kai'Sa's 58% into someone else's, and symmetry catches that for free.
 *
 *     node scripts/build-field.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CAPTURES = join(ROOT, "data/field");

// ── the window and its sources — edit these when a new capture is taken ──────

const WINDOW = { id: "vendetta-post-ban", label: "Vendetta post-ban", from: "2026-09-18" };
const MATRIX = {
  file: "boundrift-matchups-2026-09-23.txt",
  source: {
    id: "boundrift",
    name: "BoundRift",
    url: "https://boundrift.com/matchups",
    retrieved: "2026-09-23",
    covers:
      "Tournament games, Vendetta post-ban (Ekko, Recurrent and Stacked Deck banned 18 Sep), all players. " +
      "The page heads 14,083 games; its Legend-vs-Legend cells hold 13,215. The matrix has no mirror cells, so the gap is at least partly mirrors; the page does not say. " +
      "Pairings under 5 games are not published.",
  },
};
const TIERS = {
  file: "hextech-snapshot-2026-09-22.txt",
  source: {
    id: "hextech",
    name: "Hextech Analytics",
    url: "https://hextechanalytics.com/meta/snapshots/2026-09-22",
    retrieved: "2026-09-23",
    covers: "Meta Snapshot 7, published 22 Sep 2026: editorial post-ban tiers (S–D), results through 20 Sep.",
  },
};

// ── Legends, by "Champion, Title" ────────────────────────────────────────────

const pool = JSON.parse(readFileSync(join(ROOT, "apps/web/public/cards.json"), "utf8")).cards;
const legendId = new Map();
for (const c of pool) {
  if (!c.types.includes("legend")) continue;
  const title = c.name.replace(/ - Starter$/, "");
  legendId.set(`${c.championTag}, ${title}`, c.printings[0].id);
}
const idOf = (name) => {
  const id = legendId.get(name);
  if (!id) throw new Error(`No Legend in the card index is called "${name}".`);
  return id;
};

// ── the matrix ───────────────────────────────────────────────────────────────

const [head, ...lines] = readFileSync(join(CAPTURES, MATRIX.file), "utf8").trim().split("\n");
const cols = head.split(";");
const rows = new Map();
for (const line of lines) {
  const [name, wins, losses, cells] = line.split("|");
  const parsed = cells.split(",").map((c) => (c ? c.split("-").map(Number) : null));
  if (parsed.length !== cols.length) throw new Error(`${name}: ${parsed.length} cells, ${cols.length} columns.`);
  rows.set(name, { wins: Number(wins), losses: Number(losses), cells: parsed });
}

const pairings = [];
const problems = [];
for (const [a, row] of rows) {
  const i = cols.indexOf(a);
  row.cells.forEach((cell, j) => {
    if (!cell) return;
    const b = cols[j];
    const mirror = rows.get(b)?.cells[i];
    if (!mirror || mirror[0] !== cell[1] || mirror[1] !== cell[0]) {
      problems.push(`${a} vs ${b} is ${cell.join("-")}, and ${b} vs ${a} is ${mirror?.join("-") ?? "blank"}.`);
    }
    if (j > i) pairings.push({ a: idOf(a), b: idOf(b), wins: cell[0], losses: cell[1] });
  });
}
if (problems.length) {
  console.error(`The capture disagrees with itself in ${problems.length} place(s):\n  ${problems.join("\n  ")}`);
  process.exit(1);
}

// ── tiers ────────────────────────────────────────────────────────────────────

const tiers = new Map();
for (const line of readFileSync(join(CAPTURES, TIERS.file), "utf8").trim().split("\n")) {
  const [rank, tier, name] = line.split("|");
  tiers.set(name, { tier, rank: Number(rank), source: TIERS.source.id });
}

const names = [...new Set([...cols, ...tiers.keys()])].sort();
const legends = names.map((name) => {
  const row = rows.get(name);
  return {
    legendCardId: idOf(name),
    name,
    wins: row ? row.wins : null,
    losses: row ? row.losses : null,
    ...(tiers.has(name) ? { tier: tiers.get(name) } : {}),
  };
});

const snapshot = {
  schema: "forge.field/1",
  note: "GENERATED by scripts/build-field.mjs from data/field/*.txt — do not edit by hand. Figures © their sources, used with attribution (D-068).",
  window: WINDOW,
  sources: [MATRIX.source, TIERS.source],
  unpublishedBelow: 5,
  legends,
  pairings,
};

const json = JSON.stringify(snapshot, null, 1) + "\n";
writeFileSync(join(ROOT, "data/field.json"), json);
writeFileSync(join(ROOT, "apps/web/public/field.json"), json);
const games = pairings.reduce((a, p) => a + p.wins + p.losses, 0);
console.log(
  `field.json — ${WINDOW.label}: ${legends.length} Legends, ${pairings.length} pairings, ${games} games, ${tiers.size} tiers.`,
);
